USE loginoo;

DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS CONTATOS;

CREATE TABLE USUARIO (
	id INT PRIMARY KEY AUTO_INCREMENT,
	
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(150) NOT NULL,
	senha varchar(255) NOT NULL
);

CREATE TABLE CONTATOS (
	id INT PRIMARY KEY AUTO_INCREMENT,
	id_usuario INT NOT NULL,
	nome VARCHAR(100) NOT NULL,
	telefone VARCHAR(15),
	email VARCHAR(100),
	FOREIGN KEY(id_usuario) REFERENCES USUARIO(id)
);